---
# tasks file for na-ontap-cluster-config
- name: Setup licenses
  na_ontap_license:
    state: present
    license_codes: "{{ license_codes }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  when: license_codes != None
- name: Assign Disks
  na_ontap_disks:
    node: "{{ item }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  with_items:
    "{{ disks }}"
  when: disks != None
- name: Set Login Message
  na_ontap_motd:
    state: present
    vserver: "{{ cluster }}"
    message: "{{ motd }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  when: motd != None
- name: Setup DNS
  na_ontap_dns:
    state: present
    vserver: "{{ cluster }}"
    domains: "{{ item.dns_domains }}"
    nameservers: "{{ item.dns_nameservers }}"
    use_rest: Never  # Needed this to get beyond a "duplicate entry" error
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  with_items:
    "{{ dns }}"
  when: dns != None
- name: Set NTP Server
  na_ontap_ntp:
    state: present
    server_name: "{{ item.server_name }}"
    version: "{{ item.version }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  with_items:
    "{{ ntp }}"
  when: ntp != None
- name: Create SNMP community
  na_ontap_snmp:
    community_name: "{{ item.community_name }}"
    access_control: "{{ item.access_control }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  with_items:
    "{{ snmp }}"
  when: snmp != None
- name: Create Aggregates
  na_ontap_aggregate:
    state: present
    service_state: online
    name: "{{ item.name | replace('-','_') }}"
    nodes: "{{ item.node }}"
    disk_count: "{{ item.disk_count }}"
    raid_size: "{{ item.max_raid }}"
    is_mirrored: "{{ item.mirror | default('false') }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  with_items:
    "{{ aggrs }}"
  when: aggrs != None
- name: Remove ports from Default broadcast domain
  na_ontap_broadcast_domain_ports:
    state: absent
    broadcast_domain: Default
    ports: "{{ item.node }}:{{ item.port }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  with_items:
    "{{ ports }}"
  when: ports != None

# Configure flowcontrol and autonegotiate.
# Skip MTU for now b/c we have to configure IFGroup first.
- name: Modify Net Port
  na_ontap_net_port:
    state: present
    node: "{{ item.node }}"
    port: "{{ item.port }}"
#    mtu: "{{ item.mtu }}"
    autonegotiate_admin: "{{ item.autonegotiate | default(autonegotiate) }}"
    flowcontrol_admin: "{{ item.flowcontrol | default(flowcontrol) }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  with_items:
    "{{ ports }}"
  when: ports != None
- name: Create Interface Group
  na_ontap_net_ifgrp:
    state: present
    distribution_function: "{{ distribution_function }}"
    name: "{{ item.name }}"
    ports: "{{ item.ports }}"
    mode: "{{ item.mode | default(ifgrp_mode) }}"
    node: "{{ item.node }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  with_items:
    "{{ ifgrps  }}"
  when: ifgrps != None

# Set MTU - Interface group must be configured first.
- name: Modify Net Port
  na_ontap_net_port:
    state: present
    node: "{{ item.node }}"
    port: "{{ item.name }}"
    mtu: "{{ item.mtu }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  with_items:
    "{{ ifgrps }}"
  when: ifgrps != None
- name: Create VLAN
  na_ontap_net_vlan:
    state: present
    vlanid: "{{ item.id }}"
    node: "{{ item.node }}"
    parent_interface: "{{ item.parent }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  with_items:
    "{{ vlans }}"
  when: vlans != None
- name: create broadcast domain
  na_ontap_broadcast_domain:
    state: present
    broadcast_domain: "{{ item.name }}"
    mtu: "{{ item.mtu }}"
    ipspace: "{{ bcast_ipspace }}"
    ports: "{{ item.ports }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  with_items:
    "{{ bcasts }}"
  when: bcasts != None
- name: Create Intercluster Lif
  na_ontap_interface:
    state: present
    interface_name: "{{ item.name }}"
    home_port: "{{ item.port }}"
    home_node: "{{ item.node }}"
    role: intercluster
    admin_status: up
    failover_policy: local-only
    is_auto_revert: true
    address: "{{ item.address }}"
    netmask: "{{ item.netmask }}"
    vserver: "{{ cluster }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"
  with_items:
    "{{ inters }}"
  when: inters != None

# Added common configuration itesm

- name: Enable Autosupport Configuration
  na_ontap_autosupport:
    state: present
    node_name: "{{ item.node }}"
    proxy_url: "{{ item.proxy_url }}"
    transport: "{{ item.transport }}"
    hostname_in_subject: "{{ item.hostsubj | default('false') }}"
    from_address: "{{ item.from }}"
    noteto: "{{ item.noteto }}"
    to_addresses: "{{ item.to }}"
    partner_addresses: "{{ item.partner | default(omit) }}"
    mail_hosts: "{{ item.mailhosts }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"

  with_items: "{{ asup_config }}"
  when: asup_config is defined and asup_config != None

- name: Setup Service Processor (SP CONFIG)
  na_ontap_service_processor_network:
    state: present
    node: "{{ item.node }}"
    address_type: ipv4
    dhcp: none
    is_enabled: true
    ip_address: "{{ item.ip_address }}"
    gateway_ip_address: "{{ item.gateway_ip_address }}"
    netmask: "{{ item.netmask }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    https: true
    validate_certs: "{{ validate_certs }}"

  with_items: "{{ sp_config }}"
  when: sp_config is defined and sp_config != None
