---
- hosts: localhost
  gather_facts: false
  name: Basic Connectivity Test
  collections:
  - netapp.ontap

  vars:
    login: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  vars_files:
  - vars_files.yml
  - password.yml
  vars_prompt:
  - name: "netapp_password"
    prompt: "Enter the NetApp Admin Password"
    private: yes
  
  tasks:
  - name: 'Connectivity Test & Display ONTAP_info: All'
    na_ontap_info:
      state: info
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    register: ontap_info
  - debug:
        msg: "{{ ontap_info.ontap_info }}"
