---
###
# Variables for ONTAP cluster setup & config
cluster_name: sandbox
cluster_netmask: 255.255.255.0
cluster_gateway: 192.168.7.1

###
# Cluster and network services config
cluster:
  name: "{{ cluster_name }}"
  loc: "{{ location }}" # 'system snmp location'

  net:
    mgmt: 192.168.7.200
    netmask: 255.255.255.0
    gateway: 192.168.7.1

    # Node & SVM Network IP address Information
    node1:
      mgmt_ip: 192.168.7.201
      sp:
        ip: 192.168.7.xx
        netmask: "{{ cluster_netmask }}"
        gateway: "{{ cluster_gateway }}"
      icl:
        ip: 192.168.7.202
        netmask: "{{ cluster_netmask }}"
        gateway: "{{ cluster_gateway }}"
      svm_lif1:
        ip: 192.168.7.205
        netmask: "{{ cluster_netmask }}"
        gateway: "{{ cluster_gateway }}"
    node2:
      mgmt_ip: 192.168.7.203
      sp:
        ip: 192.168.7.xx
        netmask: "{{ cluster_netmask }}"
        gateway: "{{ cluster_gateway }}"
      icl:
        ip: 192.168.7.204
        netmask: "{{ cluster_netmask }}"
        gateway: "{{ cluster_gateway }}"
      svm_lif1:
        ip: 192.168.7.206
        netmask: "{{ cluster_netmask }}"
        gateway: "{{ cluster_gateway }}"

# Node Configuration Info
location: ExampleLab - 1234 Example St, Seattle, WA 12345
contact: "netapp-admins@example.local"
motd:
  banner: |
    ################ TEST BANNER ################
    # This system is currently in testing state #
    #############################################
  message: |
    Welcome!
    Please note: This system is not ready for production yet!
timezone: America/Los_Angeles
snmp:
  - community_name: public
    access_control: ro
snmp_traphosts:
  - 10.61.102.5
aggrs:
  - {
    name: "{{ cluster_name }}_01_SSD_1",
    node: "{{ cluster_name }}-01",
    disk_count: 24,
    raid_size: 24,
    raid_type: raid_dp,
    is_mirrored: false,
  }
  - {
    name: "{{ cluster_name }}_02_SSD_1",
    node: "{{ cluster_name }}-02",
    disk_count: 24,
    raid_size: 24,
    raid_type: raid_dp,
    is_mirrored: false,
  }
inters:
  - {
    name: "{{ cluster_name }}-01_ic1",
    node: "{{ cluster_name }}-01",
    port: e0c,
    address: "{{ cluster.net.node1.icl.ip }}",
    netmask: "{{ cluster.net.node1.icl.netmask }}",
  }
  - {
    name: "{{ cluster_name }}-02_ic1",
    node: "{{ cluster_name }}-02",
    port: e0c,
    address: "{{ cluster.net.node2.icl.ip }}",
    netmask: "{{ cluster.net.node2.icl.netmask }}",
  }

vservers:
  - name: vs0
    protocol:
      - iscsi
      - nfs
      - nvme
    lifs:
      - {
        lif: data_nas_1,
        service_policy: "default-data-files",
        address: 192.168.7.203,
        node: "{{ cluster_name }}-01",
        port: e0d,
        netmask: 255.255.255.0,
      }
      - {
        lif: data_iscsi_1,
        service_policy: "default-data-iscsi",
        address: 192.168.7.204,
        node: "{{ cluster_name }}-01",
        port: e0d,
        netmask: 255.255.255.0,
      }
      - {
        lif: data_nvme_1,
        service_policy: "default-data-nvme-tcp",
        address: 192.168.7.205,
        node: "{{ cluster_name }}-01",
        port: e0d,
        netmask: 255.255.255.0,
      }
    routes:
      - { destination: 0.0.0.0/0, gateway: 192.168.7.1, metric: 20 }
    nameservers:
      - 192.168.7.3
    domains:
      - example.local
    # cifs:
    #   cifs_server_name: test20vs0
    #   ou:
    #   domain: lab.local
    #   domain_tunnel: true
    nfs:
      nfsv3: enabled
      nfsv4: enabled
      nfsv41: disabled

# SVM Configuration Info
vserver: ontap-vs01

# SVM Configuration Settings & Network IP address Information
svm:
  name: "{{ vserver }}"
  rootvol: "{{ vserver | replace('-','_') }}"
  netmask: "{{ cluster_netmask }}"
  gateway: "{{ cluster_gateway }}"
  dns_domain: "{{ cluster.dns.domain | default('example.local') }}"
  dns_srvrs: "{{ cluster.dns.srvrs | default('192.168.7.3') }}"
  aggrs: "{{ cluster.aggr.name }}_01_aggr1,{{ cluster.aggr.name }}_02_aggr1"
  aggr_list: "[  ]"
  protocol: nfs
