###
#  Provides the first aggregate that matches the aggr_type or storage-type being searched for
#  includes:
#     'aggr_type' for target storage media
#     'size' requested / needed
#     'used_cap' as a thresold to limit overprovisioning aggregates
###
---
- hosts: localhost
  name: Select Aggregate
  gather_facts: false
  collections:
    - netapp.ontap
  
  vars:
    # aggr_type: ssd                      # AFF, or flash-based aggrs
    aggr_type: hdd                      # FAS, non-flash
    used_cap: 80                        # Aggr % utilization threshold
    size: 1                             # Space available in TB
    netapp_hostname: 192.168.7.200
    netapp_username: admin
    netapp_password: netapp1234
    https: true
    validate_certs: false


  tasks:
  - name: Gather aggregate facts
    na_ontap_info:
      gather_subset: aggregate_info
      hostname: "{{ netapp_hostname }}"
      query:                            # Examaple to filter for storage-type
        aggr-attributes:
          aggr-raid-attributes:
            aggregate-type: "{{ aggr_type }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: "{{ https }}"
      validate_certs: "{{ validate_certs }}"
    register: netapp_info
  - set_fact:
      aggr_name: "{{ item }}"
    with_items: "{{ netapp_info.ontap_info.aggregate_info }}"
    when: 
    - aggr_name is not defined
    - netapp_info.ontap_info.aggregate_info[item].aggr_space_attributes.size_available | int / 1024 / 1024 / 1024  > size
    - netapp_info.ontap_info.aggregate_info[item].aggr_space_attributes.percent_used_capacity | int < used_cap
  - debug:
      msg: "{{ aggr_name }}"
