###
#  Ansible configuration vars file for:
#  A basic VSIM with standard ONTAP cluster & vserver configuration
#  with: 
#   - 6 NICs
#   - 28 disks - 25 spares
###

###
# Broadcast Domain name varibles
bd:
  mgmt:         mgmt  # e0c ports (VSIM)
  nas:          data  # a0a ports

# Broadcast-domain split: Active Management ports
bcd:
  split_ports:
  # - origin_bd:    Default
  #   new_bd:       "{{ bd.mgmt }}"
  #   ports:        '["{{ cluster }}-01:e0M", "{{ cluster }}-02:e0M"]'
  - origin_bd:  Default
    new_bd:     "{{ bd.mgmt }}"
    ports:      '["{{ clus.name }}-01:e0c", "{{ clus.name }}-02:e0c"]'


###
# Autosupport Configuration Varibles
asup:

  # Standard Config varibles
  proxy_url:
  transport:    smtp
  noteto:       admin@example.local
  mailhosts:    192.168.7.3
  hostsubj:     true
  to:           'netapp_admin@{{ dns_domain }}'
  from:         '{{ clus.name }}@{{ dns_domain }}'
  partner:

  # Node Specific Config parameters - node list
asup_config:
- node:       '{{ clus.name }}-01'
  proxy_url:  '{{ asup.proxy_url }}'
  transport:  '{{ asup.transport }}'
  mailhosts:  '{{ asup.mailhosts }}'
  hostsubj:   '{{ asup.hostsubj }}'
  from:       '{{ asup.from }}'
  to:         '{{ asup.to }}'
  noteto:     '{{ asup.noteto }}'
  partner:    '{{ asup.partner }}'
- node:       '{{ clus.name }}-02'
  proxy_url:  '{{ asup.proxy_url }}'
  transport:  '{{ asup.transport }}'
  mailhosts:  '{{ asup.mailhosts }}'
  hostsubj:   '{{ asup.hostsubj }}'
  from:       '{{ asup.from }}'
  to:         '{{ asup.to }}'
  noteto:     '{{ asup.noteto }}'
  partner:    '{{ asup.partner }}'


###
# SVM Configuration Settings
svm_name:     "{{ vserver }}"
svm:            
  name:         "{{ svm_name }}"
  root:         "{{ svm_name | replace('-','_') }}"
  aggrs:        "{{ clus.aggr }}_01_aggr1,{{ clus.aggr }}_02_aggr1"
  dns_domain:   "{{ svm.dns_domain }}"
  dns_srvrs:    "{{ dns_srvrs }}"
  netmask:      "{{ svm.netmask }}"    # Replace with IP if not the same
  gateway:      "{{ svm.gateway }}"    # Replace with IP if not the same
  aggr_list:    '[  ]'
  protocol:     nfs
  # export_policy:
  # - name:  'Data'
  #   client_match:
  #   index:
  #   ro_rule:
  #   rw_rule:
  #   super_user_security:


###
# RBAC Configuration
# User and Role Configuration Varibles
###

# role_cmds:
#   - { name: 'netapp_harvest', cmddir: 'version', level: 'readonly', svm: "{{ cluster }}" }
#   - { name: 'netapp_harvest', cmddir: 'cluster identity show', level: 'readonly', svm: "{{ cluster }}" }
#   - { name: 'netapp_harvest', cmddir: 'cluster show', level: 'readonly', svm: "{{ cluster }}" }
#   - { name: 'netapp_harvest', cmddir: 'system node show', level: 'readonly', svm: "{{ cluster }}" }
#   - { name: 'netapp_harvest', cmddir: 'statistics', level: 'readonly', svm: "{{ cluster }}" }
#   - { name: 'netapp_harvest', cmddir: 'lun show', level: 'readonly', svm: "{{ cluster }}" }
#   - { name: 'netapp_harvest', cmddir: 'network interface show', level: 'readonly', svm: "{{ cluster }}" }
#   - { name: 'netapp_harvest', cmddir: 'qos workload show', level: 'readonly', svm: "{{ cluster }}" }

user_list:
  - { name: 'harvest', app: 'ontapi', auth: 'password', role: 'readonly', pass: "{{ netapp_password }}", svm: "{{ cluster }}" }
  # - { name: 'netapp_harvest', app: 'ontapi', auth: 'password', role: 'netapp_harvest', pass: 'T3mp-p@55', svm: "{{ cluster }}" }
  # - { name: 'netapp_pse', app: 'ontapi', auth: 'password', role: 'admin', pass: 'T3mp-p@55', svm: "{{ cluster }}" }
  # - { name: 'netapp_pse', app: 'console', auth: 'password', role: 'admin', pass: 'T3mp-p@55', svm: "{{ cluster }}" }
  # - { name: 'netapp_pse', app: 'http', auth: 'password', role: 'admin', pass: 'T3mp-p@55', svm: "{{ cluster }}" }
  # - { name: 'netapp_pse', app: 'service-processor', auth: 'password', role: 'admin', pass: 'T3mp-p@55', svm: "{{ cluster }}" }
  # - { name: 'netapp_pse', app: 'ssh', auth: 'password', role: 'admin', pass: 'T3mp-p@55', svm: "{{ cluster }}" }
  # - { name: 'storage_api', app: 'ontapi', auth: 'password', role: 'admin', pass: 'T3mp-p@55', svm: "{{ cluster }}" }
  # - { name: 'storage_api', app: 'ontapi', auth: 'password', role: 'vsadmin', pass: 'T3mp-p@55', svm: "{{ svm }}" }
  # - { name: 'snmp', app: 'snmp', auth: 'usm', role: 'readonly', pass: 'T3mp-p@55', svm: "{{ svm }}" }

###
# Export-Policy Management
# Note: Replace networks that are valid to the environment & adjust as needed
###

svm_export_policy_name:
- { svm: "{{ svm.name }}", name: 'Data' }

export_policy_rules_list:
- { name: 'default', svm: "{{ svm.name }}", client_match: '192.168.7.122', protocol: nfs, ro_rule: 'sys', rw_rule: 'sys', super_user_security: 'sys' }
- { name: 'default', svm: "{{ svm.name }}", client_match: '192.168.7.0/24', protocol: any, ro_rule: 'any', rw_rule: 'none', super_user_security: 'none' }
- { name: 'Data', svm: "{{ svm.name }}", client_match: '192.168.7.0/24', protocol: nfs, ro_rule: 'any', rw_rule: 'any', super_user_security: 'sys' }
- { name: 'Data', svm: "{{ svm.name }}", client_match: '0.0.0.0/0', protocol: nfs, ro_rule: 'any', rw_rule: 'none', super_user_security: 'none' }

###
# LS Mirrors
###
ls_mirrors:
  - { aggr: "{{ cluster | replace('-','_') }}_01_aggr1", name: "{{ svm | replace('-','_') }}_root_mir1", svm: "{{ svm }}" }
  - { aggr: "{{ cluster | replace('-','_') }}_02_aggr1", name: "{{ svm | replace('-','_') }}_root_mir2", svm: "{{ svm }}" }

###
# Event Destinations & Log Forwarding
# Needs more attention to ensure configuration is correct
###



###
# Custom Modifications
###


