---
- hosts:        localhost
  name:         Basic Connectivity Test
  gather_facts: false
  collections:
    - netapp.ontap

  # Varible precedence: vars < vars_prompts < vaars_files
  vars:
    netapp_hostname:  192.168.7.200
    netapp_username:  admin
    state:            present
    
    cifs_srvr_name:   onatp-vs01
    svm:              onatp-vs01
    service_state:    stopped 
    
    id_domain:        example.local
    domain_login:     administrator
    # domain_pwd:       netapp1234

    login: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https:    true
      validate_certs: false
  vars_prompt:
    - name:     "netapp_password"
      prompt:   "Enter the NetApp Admin Password"
      private:  yes
    - name:     "domain_pwd"
      prompt:   "Enter the Windows Domain Admin Password"
      private:  yes
  # vars_files:
  #   - vars_files.yml

  tasks:
  
  - name: Modify cifs_server security - REST
    netapp.ontap.na_ontap_cifs_server:
      state:          "{{ state }}"
      name:           "{{ cifs_srvr_name }}"
      vserver:        "{{ svm }}"
      service_state:  "{{ service_state }}"
      # encrypt_dc_connection: True,
      # smb_encryption: True,
      # kdc_encryption: True,
      # smb_signing: True,
      # aes_netlogon_enabled: True,
      # ldap_referral_enabled: True,
      # session_security: seal,
      # try_ldap_channel_binding: False,
      # use_ldaps: True,
      # use_start_tls": True
      # restrict_anonymous: no_access
      domain:           "{{ id_domain }}"
      admin_user_name:  "{{ domain_login }}"
      admin_password:   "{{ domain_pwd }}"
      <<: *login
    register: response_info

  - name: Display Captured info
    debug:
        msg: "{{ response_info }}"
