# Select Provision - FlexVols
---
- name: Provision NAS '{{ vserver_name }}' Volume
  netapp.ontap.na_ontap_volume:
    state:                  present
    hostname:               "{{ netapp_hostname }}"
    username:               "{{ netapp_username }}"
    password:               "{{ netapp_password }}"
    https:                  "{{ https }}"
    validate_certs:         "{{ validate_certs }}"
    vserver:                "{{ item.svm }}"
    name:                   "{{ item.flexvol_name }}"
    aggregate_name:         "{{ item.aggr if item.aggr != None else (hostvars[inventory_hostname]['aggrs'] | random).name }}"
    size:                   "{{ item.size }}"
    size_unit:              "{{ item.size_unit              | default('gb') }}"
    size_change_threshold:  "{{ item.size_change_threshold  | default(10 | int) }}"
    junction_path:          "/{{ item.junction_path if item.junction_path is defined and not None else item.flexvol_name }}"
    user_id:                "{{ item.uid                    | default(0 | int) }}"
    group_id:               "{{ item.gid                    | default(0 | int) }}"
    unix_permissions:       "{{ item.unix_permissions       | default('755') }}"
    volume_security_style:  "{{ item.volume_security_style  | default('unix') }}"
    analytics:              "{{ item.analytics              | default(omit) }}"
    percent_snapshot_space: "{{ item.percent_snapshot_space | default(5 | int) }}"
    snapshot_policy:        "{{ item.snapshot_policy        | default('default') }}"
    snapshot_auto_delete:   "{{ item.snapshot_auto_delete   | default(omit) }}"
    tiering_policy:         "{{ item.tiering_policy         | default('none') }}"
    export_policy:          "{{ 'default' if item.protocol | lower == 'cifs' else item.export_policy | default('default') }}"
    qos_policy_group:       "{{ item.qos_policy_group       | default(omit) }}"
    qos_adaptive_policy_group: "{{ item.qos_adaptive_policy_group | default(omit) }}"
    efficiency_policy:      "{{ item.efficiency_policy      | default(omit) }}"
    logical_space_enforcement: "{{ item.logical_space_enforcement | default('false') }}"
    logical_space_reporting: "{{ item.logical_space_reporting | default('false') }}"
    max_files:              "{{ item.max_files              | default(omit) }}"
    encrypt:                "{{ item.encrypt                | default('false') }}"
    space_guarantee:        "{{ item.space_guarantee        | default(omit) }}"
    type:                   "{{ item.type                   | default('RW') }}"
    wait_for_completion:    "{{ item.wait_for_completion    | default(omit) }}"
    tags:                   "{{ item.tags                   | default(omit) }}"
    comment:                "{{ item.comment                | default(omit) }}"
  with_items:
    "{{ volumes }}"
