volumes:
  - svm: "{{ vserver_name }}"
    protocol: nfs # cifs, nfs or multi-protocol (concurrent cifs & NFS access)
    # aggr:                 "{{ inventory_hostname }}_01_aggr_1"
    aggr:         # System defined if left blank
    flexvol_name: test_nfs_01
    size: 10
    size_unit: gb
    # Optional parameters below
    comment: "This is DEV Test Volume"
    # tags:                   "test"
    # uid:                    0
    # gid:                    0
    unix_permissions: 0777
    volume_security_style: "unix"
    percent_snapshot_space: 10
  - svm: "{{ vserver_name }}"
    protocol: cifs # cifs, nfs or multi-protocol (concurrent cifs & NFS access)
    # aggr:                 "{{ inventory_hostname }}_01_aggr_2"
    aggr:         # System defined if left blank
    flexvol_name: test_ntfs_01
    size: 10
    # Optional parameters below
    # volume_security_style: "ntfs"
    comment: "This is DEV Test Volume"
  - svm: "{{ vserver_name }}"
    protocol: cifs # cifs, nfs or multi-protocol (concurrent cifs & NFS access)
    aggr: 
    flexvol_name: test_cifs_01
    size: 10
    # Optional parameters below
    # tags:                   "test"
    # uid: 0
    # gid: 0
    # unix_permissions: 0777
    # volume_security_style: "unix"
    # percent_snapshot_space: 10
    comment: "This is DEV Test NTFS Volume"
    

cifs_shares:
  - svm: "{{ vserver_name }}"
    name: test_cifs_01
    comment: "This is DEV Test CIFS Share"
    # Optional parameters below
    junction_path: /test_cifs_01
    browsable: true
    namespace_caching: true # Controls whether namespace caching is enabled
    oplocks: true
    change_notify: true
    show_previous_versions: true # Controls whether previous versions are shown
    show_snapshot: false # Controls whether snapshots are shown
    unix_symlink: local # local, widelink or disable

nfs_exports:
  - name: default
    svm: "{{ vserver_name }}"
    rule_index: 1
    client_match: ["192.168.7.125"]
    ro: any
    rw: any
    # Optional parameters below
    protocol: nfs
    su: any
    anonymous: 0
    suid: true
    ntfs_unix_security: ignore
  - name: default
    svm: "{{ vserver_name }}"
    rule_index: 2
    client_match: ["192.168.7.10"]
    ro: any
    rw: any
    # Optional parameters below
    protocol: nfs
    su: any
    anonymous: 0
    suid: false
    ntfs_unix_security: fail
  - name: default
    svm: "{{ vserver_name }}"
    rule_index: 3
    client_match: ["192.168.7.0/24"]
    ro: any
    rw: any
    # Optional parameters below
    protocol: nfs
    su: any
    anonymous: 0
    suid: false
    ntfs_unix_security: fail
  - name: default
    svm: "{{ vserver_name }}"
    rule_index: 3
    client_match: ["0.0.0.0/0"]
    ro: any
    rw: none
    # Optional parameters below
    protocol: nfs
    su: none
    anonymous: 65534
    suid: false
    ntfs_unix_security: fail
