#######################################################
# 
#   Author:     Ken Hillier
#   Date:       28 Oct 24
# 
#   Description:  Playbook that Provisions ONTAP NFS exports, SMB shares, iSCSI LUNs & NVMe namespaces.
# 
#   Dependencies:  
# 
#######################################################
---
- name: NetApp ONTAP Provision NAS / SAN
  hosts: ontap
  gather_facts: false
  collections:
    - netapp.ontap
  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      use_rest: always
  vars_files:
    - ../vars/sandbox_prov_nas.yml
  # vars_prompt:
  #   - name: admin_username
  #     prompt: AD Domain admin account
  #     default: "administrator"
  #     private: no
  #   - name: admin_password
  #     prompt: AD Domain admin account password
  #     confirm: yes
  #     private: yes
  vars:
    vserver_name: vs0


  tasks:

    - name: Print VAR for Troubleshooting
      ansible.builtin.debug: 
        msg: 
        - "{{ inventory_hostname }}"
        - "{{ ansible_host }}"
        - "{{ volumes }}"

    - import_role:
        name: ontap_prov_nas

    - import_role:
        name: ontap_prov_san

