# debug-playbook.yml
---
- name: Debug Ansible Variable Resolution
  hosts: ontap # Adjust to target specific hosts or groups
  gather_facts: false # Disable facts for simplicity, enable if needed
  vars_files:
    # - ../inventory/group_vars/vault.yml
  vars:
    # Define any test vars here for comparison if needed
    debug_test_var: "This is a test var defined in playbook vars."
    netapp_hostname: "{{ cluster.net.mgmt }}"
    # netapp_hostname: "{{ inventory_hostname }}"

  tasks:
    # - name: Show all variables (useful for inventory debugging)
    #   debug:
    #     var: hostvars[inventory_hostname]

    - name: Print netapp_hostname via cluster.net.mgmt lookup
      debug:
        msg: "netapp_hostname is {{ netapp_hostname }}"

    - name: Print netapp_hostname via inventory_hostname lookup
      debug:
        msg: "cluster_ip is {{ cluster.net.mgmt }}"

    - name: Cluster Name
      debug:
        var: cluster_name

    # - name: Print management IP for sandbox
    #   debug:
    #     var: cluster.net.node1.mgmt_ip # Expected output: 192.168.7.200 for sandbox

    # - name: Print entire aggrs structure
    #   debug:
    #     var: hostvars[inventory_hostname].aggrs

    # - name: Print the first aggregate name in aggrs
    #   debug:
    #     var: hostvars[inventory_hostname].aggrs[0].name

    # - name: Print all lif names under vservers
    #   debug:
    #     msg: "{{ item.lif }}"
    #   loop: "{{ hostvars[inventory_hostname].vservers[0].lifs }}"

    - name: Print ansible connection type
      debug:
        var: ansible_connection

    - name: Print NTP servers
      debug:
        var: time.servers

    - name: Print timezone
      debug:
        var: time.zone

    - name: Print DNS domain
      debug:
        var: dns_domain

    - name: Print DNS servers
      debug:
        var: dns_servers

    - name: Print license_codes (alias for combined licenses)
      debug:
        var: license_codes

    - name: "Print netapp_hostname via cluster.net.mgmt lookup"
      debug:
        msg:
          - "netapp_hostname is {{ inventory_hostname }}"
          - "netapp_hostname is {{ netapp_hostname | default('<|HOSTNAME UNDEFINED|>') }}"
          - "netapp_username is {{ netapp_username | default('<|USERNAME UNDEFINED|>')  }}"
          # - "netapp_password is {{ netapp_password | default('<|PASSWORD UNDEFINED|>') }}"
          - "netapp_password is {{ '<|PASSWORD SET|>' if netapp_password is defined else '<|PASSWORD UNDEFINED|>' }}"
