---
- hosts: localhost
  name: "Get Tenant Account ID from GRID-INFO Byname"
  gather_facts: false
  collections:
    - netapp.storagegrid
  vars_files:
    # - vars/vars_sg_exampleLab.yml
    # - vars/vars_sg_tenant_appid01.yml
  vars:
    grid:
      api_base_url:   https://192.168.7.215
      admin_username: root
      admin_passwd:   netapp1234
    tenant:
      # name: AppID01
      name: appid01
    grid_auth: &grid_auth
      api_url: "{{ grid.api_base_url }}"
      auth_token: "{{ auth_response.json.data }}"
      validate_certs: false

  tasks:
  ###
  # GRID API Authorization Token
    - name: Get GRID authorization token
      uri:
        url: "{{ grid.api_base_url }}/api/v3/authorize"
        method: POST
        validate_certs: false
        body_format: json
        body:
          {
            "username": "{{ grid.admin_username }}",
            "password": "{{ grid.admin_passwd }}",
            "cookie": false,
            "csrfToken": false,
          }
      register: auth_response

  ###
  # GRID INFO Collection
    - name: Get Grid INFO
      netapp.storagegrid.na_sg_grid_info:
        <<: *grid_auth
        gather_subset:
          # - all
          - grid/accounts
      register: grid_info_results

  ###
  # Debug: Print GRID-INFO Response
    # - name: Print GRID-INFO Response
    #   debug:
    #     var: grid_info_results

  ###
  # Debug: Print Tenant Account ID Byname
    - name: "Print Tenant ID for {{ tenant.name }}"
      debug:
        msg:
          # - "Tenant Name:   {{ grid_info_results.sg_info['grid/accounts'].data[0].name }}"
          # - "Tenant ID:     {{ grid_info_results.sg_info['grid/accounts'].data[0].id }}"
          # - "{{ item.name }}"
          - "Tenant Name: {{ item.name }} Tenant ID: {{ item.id }}"
      with_items:
        - "{{ grid_info_results.sg_info['grid/accounts'].data }}"
      when: item.name == tenant.name

    ###
    # Examples

    # - name: Print GRID User accountid
    #   debug:
    #     msg:
    #     - "Tenant GRID Admin:            {{ grid_info_results }}"

    # - name: Print GRID details
    #   debug:
    #     msg:
    #     - "GRID Name:               {{ grid_info_results.sg_info['grid/health/topology'].data.name }}"
    #     - "StorageGRID Version:     {{ grid_info_results.sg_info['grid/config/product-version'].data.productVersion }}"

    # - name: Print GRID nodes
    #   debug:
    #     msg:
    #     - "Data Center:        {{ item.0.name }}"
    #     - "Node Name:          {{ item.1.name }}"
    #     - "Node Type:          {{ item.1.type }}"
    #   with_subelements:
    #   - "{{ grid_info_results.sg_info['grid/health/topology'].data.children }}"
    #   - children
    #   loop_control:
    #     label: "{{ item.0.name }} - {{ item.1.name }}"

    # - name: Print GRID details
    #   debug:
    #     var: grid_info_results
    #     msg:
    #     - "Tenant:            {{ grid_info_results.sg_info['grid/accounts'].data.name }}"
