---
- hosts: localhost
  name: "Get GRID Info"
  gather_facts: false
  collections:
    - ansible.builtin
    - netapp.storagegrid
  vars_files:
    - vars/creds_sg_exampleLab.yml
  vars:
    grid_auth: &grid_auth
      api_url: "{{ cred.api_base_url }}"
      auth_token: "{{ auth_response.json.data }}"
      validate_certs: false

  tasks:
    - name: Get GRID authorization token
      ansible.builtin.uri:
        url: "{{ cred.api_base_url }}/api/v3/authorize"
        method: POST
        validate_certs: false
        body_format: json
        body:
          {
            "username": "{{ cred.admin_username }}",
            "password": "{{ cred.admin_passwd }}",
            "cookie": false,
            "csrfToken": false,
          }
      register: auth_response

    # - name: Get GRID authorization token
    #   ansible.builtin.uri:
    #     url: "{{ grid.api_base_url }}/api/v3/authorize"
    #     method: POST
    #     validate_certs: false
    #     body_format: json
    #     body:
    #       {
    #         "username": "gridadmin1",
    #         "password": "exampleGRID",
    #         "cookie": false,
    #         "csrfToken": false,
    #       }
    #   register: auth_response

    - name: Get Grid INFO
      netapp.storagegrid.na_sg_grid_info:
        gather_subset:
          # - all
          # - versions
          # - grid/health/topology
          # - grid/config/product-version
          # - grid/accounts
          - grid/groups
          # - grid/users/root
          # - grid/users
        <<: *grid_auth
      register: grid_info_results

    - name: Print GRID Response
      ansible.builtin.debug:
        var: grid_info_results
        # msg:
        # - "Tenant:            {{ grid_info_results.sg_info['grid/accounts'].data.name }}"

    # - name: Print GRID Accounts Response
    #   ansible.builtin.debug:
    #     msg:
    #       # - "Tenant:            {{ grid_info_results.sg_info['grid/accounts'].data.name }}"
    #       - "Tenant:            {{ grid_info_results.sg_info['grid/accounts'].data.name | from_json }}"

    ###
    # Examples

    # - name: Print GRID User accountid
    #   ansible.builtin.debug:
    #     msg:
    #     - "Tenant GRID Admin:            {{ grid_info_results }}"

    # - name: Print GRID details
    #   ansible.builtin.debug:
    #     msg:
    #     - "GRID Name:               {{ grid_info_results.sg_info['grid/health/topology'].data.name }}"
    #     - "StorageGRID Version:     {{ grid_info_results.sg_info['grid/config/product-version'].data.productVersion }}"

    # - name: Print GRID nodes
    #   ansible.builtin.debug:
    #     msg:
    #     - "Data Center:        {{ item.0.name }}"
    #     - "Node Name:          {{ item.1.name }}"
    #     - "Node Type:          {{ item.1.type }}"
    #   with_subelements:
    #   - "{{ grid_info_results.sg_info['grid/health/topology'].data.children }}"
    #   - children
    #   loop_control:
    #     label: "{{ item.0.name }} - {{ item.1.name }}"

    # - name: Print GRID details
    #   ansible.builtin.debug:
    #     var: grid_info_results
    #     msg:
    #     - "Tenant:            {{ grid_info_results.sg_info['grid/accounts'].data.name }}"
