---
- hosts: localhost
  name: "Get Org Info"
  gather_facts: no
  collections:
  - netapp.storagegrid
  vars_files:
  - vars/vars_sg_exampleLab.yml
  vars:
    tenant:
      name:           AppID01
      id:             '38493884429242321796'
      admin_username: root
      admin_passwd:   netapp1234
    
    find_tenant_id:   false  # Set to true to enable tenant.id lookup byname

    ###
    # Authentication Bearer Tokens 
    # Grid Authorization Token
    grid_auth: &grid_auth
      api_url:        "{{ grid.api_base_url }}"
      auth_token:     "{{ auth_response.json.data }}"
      validate_certs: false
    # Tenant Authorization Token
    tenant_auth: &org_auth
      api_url:        "{{ grid.api_base_url }}"
      auth_token:     "{{ tenant_auth_response.json.data }}"
      validate_certs: false

  tasks:

  ###
  # GRID API Authorization Token
  - name: Get GRID authorization token
    uri:
      url: "{{ grid.api_base_url }}/api/v3/authorize"
      method: POST
      validate_certs: false
      body_format: json
      body:
        {
          "username": "{{ grid.admin_username }}",
          "password": "{{ grid.admin_passwd }}",
          "cookie": false,
          "csrfToken": false,
        }
    register: auth_response

  ###
  # Lookup Tenant account_id - set find_account_id to `true` 
  - name: Lookup Tenant account_id byname
    block:

  ###
  # GRID INFO Collection
    - name: Get Grid INFO
      netapp.storagegrid.na_sg_grid_info:
        <<: *grid_auth
        gather_subset:
          # - all
          - grid/accounts
      register: grid_info_results

  ###
  # Debug: Print GRID-INFO Response
    # - name: Print GRID-INFO Response
    #   debug:
    #     var: grid_info_results

  ###
  # Debug: Print Tenant Account ID Byname
    # - name: "Print Tenant ID for {{ tenant.name }}"
    #   debug:
    #     msg:
    #       - "Tenant Name: {{ item.name }} Tenant ID: {{ item.id }}"
    #   with_items:
    #     - "{{ grid_info_results.sg_info['grid/accounts'].data }}"
    #   when: item.name == tenant.name

  ###
  # Find account_id for given tenant name
    - name: Set_Fact - tenant_id
      set_fact:
        tenant.id: "{{ item.id }}"
      with_items:
        - "{{ grid_info_results.sg_info['grid/accounts'].data }}"
      when: item.name|lower == tenant.name|lower

  ###
  # Debug: Print varible value
    # - name: 'DEBUG: Print Varible: tenant_id'
    #   debug:
    #     msg: "from set_fact: {{ tenant_id }}"

    when: find_tenant_id is true 
  
  # End block
  ###

  ###
  # Tenant Authorization Token
  - name: Get Tenant Administrator user authorization token
    uri:
      url: "{{ grid.api_base_url }}/api/v3/authorize"
      method: POST
      validate_certs: false
      body_format: json
      body:
        {
          "accountId":  "{{ tenant.id }}",
          "username":   "{{ tenant.admin_username }}",
          "password":   "{{ tenant.admin_passwd }}",
          "cookie": false,
          "csrfToken": false,
        }
    register: tenant_auth_response

  ###
  # Debug: Print varible value
  # - name: Print AUTH Token Data
  #   debug:
  #     msg: "Authorization Bearer Token: {{ tenant_auth_response.json.data }}"

  ###
  # OGR-INFO Get: ALL
  - name: Get ORG Info
    netapp.storagegrid.na_sg_org_info:
      gather_subset:
      - all
      # - org/containers
      # - org/users/root
      <<: *org_auth
    register: grid_info_results

  ###
  # Debug: Print varible value
  - name: Print GRID Response
    debug:
      var: grid_info_results

  ###
  # Debug: Print Containers within Tenant
  - name: "Print Containers for {{ tenant.name }}"
    debug:
      msg:
      - "Container Instance:  {{ index }}"
      - "Bucket Name:         {{ item.name }}"
      # - "Bytes: {{ item.[index].dataBytes }}"
      # - "Bytes: {{ grid_info_results.sg_info['org/containers'].data.[index].dataBytes }}"
      # - "Object Count: {{ grid_info_results.sg_info['org/containers'].data.[index].objectCount }}"
      
      # - "Bucket Name: {{ item.name }} - dataBytes: {{ item.dataBytes }} objectCount: {{ item.objectCount }}"
    with_items:
      - "{{ grid_info_results.sg_info['org/containers'].data }}"
    loop_control:
      # label: "{{ item.name }}"
      label: ''
      index_var: index
  
  ###
  # DEBUG Example 

    # Display Select(relevant) Informaiton from Performance Service Levels (PSLs)
    # - debug:
    #     msg:
    #       {
    #         "PSL Name":                   "{{ item.name }}",
    #         "PSL Description":            "{{ item.description }}",
    #         "PSL SLA (Expected)":         "{{ item.iops.expected_iops_per_tb }}",
    #         "PSL SLO (Peak)":             "{{ item.iops.peak_iops_per_tb }}",
    #         "PSL MIN IOPs":               "{{ item.iops.absolute_min_iops }}",
    #         "PSL Peak Allocation Policy": "{{ item.iops.peak_iops_allocation_policy }}",
    #         "PSL Latency":                "{{ item.latency }}",
    #         "PSL Syste-Defined":          "{{ item.system_defined }}"
    #       }
    #   name: 'Display API GET PSL results'

    #   loop: "{{ org_info_results.json.records }}"
    #   loop_control:
    #     label: "{{ item.name }}"
    #   when:  item.system_defined == true