---
- hosts: localhost
  name: "Get Org Info && List Buckets"
  gather_facts: no
  collections:
  - netapp.storagegrid
  vars_files:
  - vars/vars_sg_exampleLab.yml
  vars:
    # tenant_mgr:         gridadmin1
    # tenant_mgr_passwd:  exampleGRID
    tenant:
      name:           AppID01
      admin_username: root
      admin_passwd:   netapp1234
    
    # find_tenant_id:   true  # Set to true to enable tenant_id lookup byname
    # tenant_id:              # Enter account_id if not looking up byname && find_tenant_id == false

    ###
    # Authentication Bearer Tokens 
    # Grid Authorization Token
    grid_auth: &grid_auth
      api_url:        "{{ grid.api_base_url }}"
      auth_token:     "{{ auth_response.json.data }}"
      validate_certs: false
    # Tenant Authorization Token
    tenant_auth: &org_auth
      api_url:        "{{ grid.api_base_url }}"
      auth_token:     "{{ tenant_auth_response.json.data }}"
      validate_certs: false

  tasks:

  ###
  # GRID API Authorization Token
  - name: Get GRID authorization token
    uri:
      url: "{{ grid.api_base_url }}/api/v3/authorize"
      method: POST
      validate_certs: false
      body_format: json
      body:
        {
          "username": "{{ grid.admin_username }}",
          "password": "{{ grid.admin_passwd }}",
          "cookie": false,
          "csrfToken": false,
        }
    register: auth_response

###
# Lookup Tenant account_id - set find_account_id to `true` 
  - name: Lookup Tenant account_id byname
    block:

  ###
  # GRID INFO Collection
    - name: Get Grid INFO
      netapp.storagegrid.na_sg_grid_info:
        <<: *grid_auth
        gather_subset:
          # - all
          - grid/accounts
      register: grid_info_results

  ###
  # Debug: Print GRID-INFO Response
    # - name: Print GRID-INFO Response
    #   debug:
    #     var: grid_info_results

  ###
  # Debug: Print Tenant Account ID Byname
    # - name: "Print Tenant ID for {{ tenant.name }}"
    #   debug:
    #     msg:
    #       - "Tenant Name: {{ item.name }} Tenant ID: {{ item.id }}"
    #   with_items:
    #     - "{{ grid_info_results.sg_info['grid/accounts'].data }}"
    #   when: item.name == tenant.name

  ###
  # Find account_id for given tenant name
    - name: Set_Fact - tenant_id
      set_fact:
        tenant_id: "{{ item.id }}"
      with_items:
        - "{{ grid_info_results.sg_info['grid/accounts'].data }}"
      when: item.name|lower == tenant.name|lower

  ###
  # Debug: Print varible value
    # - name: 'DEBUG: Print Varible: tenant_id'
    #   debug:
    #     msg: "from set_fact: {{ tenant_id }}"

    # when: find_tenant_id is true 
  
  # End block
  ###

  ###
  # Tenant Authorization Token
  - name: Get Tenant Administrator user authorization token
    uri:
      url: "{{ grid.api_base_url }}/api/v3/authorize"
      method: POST
      validate_certs: false
      body_format: json
      body:
        {
          "accountId":  "{{ tenant_id }}",
          "username":   "{{ tenant.admin_username }}",
          "password":   "{{ tenant.admin_passwd }}",
          "cookie": false,
          "csrfToken": false,
        }
    register: tenant_auth_response

  ###
  # Debug: Print varible value
  # - name: Print AUTH Token Data
  #   debug:
  #     msg: "Authorization Bearer Token: {{ tenant_auth_response.json.data }}"

  - name: Get ORG Info
    netapp.storagegrid.na_sg_org_info:
      gather_subset:
      # - all
      - org/containers
      <<: *org_auth
    register: grid_info_results

  ###
  # Debug: Print varible value
  - name: Print GRID Response
    debug:
      var: grid_info_results

  # - name: Print GRID details
  #   debug:
  #     msg:
  #     - "GRID Name:               {{ grid_info_results.sg_info['grid/health/topology'].data.name }}"
  #     - "StorageGRID Version:     {{ grid_info_results.sg_info['grid/config/product-version'].data.productVersion }}"

  # - name: Print GRID nodes
  #   debug:
  #     msg:
  #     - "Data Center:        {{ item.0.name }}"
  #     - "Node Name:          {{ item.1.name }}"
  #     - "Node Type:          {{ item.1.type }}"
  #   with_subelements:
  #   - "{{ grid_info_results.sg_info['grid/health/topology'].data.children }}"
  #   - children
  #   loop_control:
  #     label: "{{ item.0.name }} - {{ item.1.name }}"

  # - name: Print GRID Response
  #   debug:
  #     var: grid_info_results
  #     # msg:
  #     # - "Tenant:            {{ grid_info_results.sg_info['grid/accounts'].data.name }}"

  ###
  # Debug: Print varible value
  # - name: Print GRID Response
  #   debug:
  #     # var: grid_info_results
  #     msg:
  #     - "Bucket:            {{ grid_info_results.sg_info['org/containers'].data }}"

  ###
  # Debug: Print Containers within Tenant
  - name: "Print Containers for {{ tenant.name }}"
    debug:
      msg:
        - "Bucket Name: {{ item.name }}"
    with_items:
      - "{{ grid_info_results.sg_info['org/containers'].data }}"

