---
- hosts: localhost
  name: "Get Org Info"
  gather_facts: false
  collections:
    - ansible.builtin
    - netapp.storagegrid
  vars_files:
  - vars/creds_sg_exampleLab.yml
  vars:
    tenant:
      name:           AppID01
      id:             '27370536033373718633'
      admin_username: root
      admin_passwd:   netapp1234

    find_tenant_id:   false  # Set to true to enable tenant.id lookup byname

    ###
    # Authentication Bearer Tokens 
    # Grid Authorization Token
    grid_auth: &grid_auth
      api_url:        "{{ cred.api_url }}"
      auth_token:     "{{ auth_response.json.data }}"
      validate_certs: false
    # Tenant Authorization Token
    tenant_auth: &org_auth
      api_url:        "{{ cred.api_url }}"
      auth_token:     "{{ tenant_auth_response.json.data }}"
      validate_certs: false

  tasks:

    ###
    # GRID API Authorization Token
    - name: Get GRID authorization token
      ansible.builtin.uri:
        url: "{{ cred.api_url }}/api/v3/authorize"
        method: POST
        validate_certs: false
        body_format: json
        body:
          {
            "username": "{{ cred.admin_username }}",
            "password": "{{ cred.admin_passwd }}",
            "cookie": false,
            "csrfToken": false,
          }
      register: auth_response

    ###
    # Lookup Tenant account_id - set find_account_id to `true` 
    - name: Lookup Tenant account_id byname
      block:

      ###
      # GRID INFO Collection
        - name: Get Grid INFO
          netapp.storagegrid.na_sg_grid_info:
            <<: *grid_auth
            gather_subset:
              # - all
              # - grid/accounts
          register: grid_info_results

      ###
      # Debug: Print GRID-INFO Response
      # - name: Print GRID-INFO Response
      #   ansible.builtin.debug:
      #     var: grid_info_results

      ###
      # Debug: Print Tenant Account ID Byname
      # - name: "Print Tenant ID for {{ tenant.name }}"
      #   ansible.builtin.debug:
      #     msg:
      #       - "Tenant Name: {{ item.name }} Tenant ID: {{ item.id }}"
      #   with_items:
      #     - "{{ grid_info_results.sg_info['grid/accounts'].data }}"
      #   when: item.name == tenant.name

      ###
      # Find account_id for given tenant name
        - name: Set_Fact - tenant_id
          ansible.builtin.set_fact:
            tenant.id: "{{ item.id }}"
          with_items:
            - "{{ grid_info_results.sg_info['grid/accounts'].data }}"
          when: item.name|lower == tenant.name|lower

      ###
      # Debug: Print varible value
      # - name: 'DEBUG: Print Varible: tenant_id'
      #   debug:
      #     msg: "from set_fact: {{ tenant_id }}"

      when: find_tenant_id is true
      # End block
      ###

    ###
    # Tenant Authorization Token
    - name: Get Tenant Administrator user authorization token
      ansible.builtin.uri:
        url: "{{ cred.api_url }}/api/v3/authorize"
        method: POST
        validate_certs: false
        body_format: json
        body:
          {
            "accountId":  "{{ tenant.id }}",
            "username":   "{{ tenant.admin_username }}",
            "password":   "{{ tenant.admin_passwd }}",
            "cookie": false,
            "csrfToken": false,
          }
      register: tenant_auth_response

    ###
    # Debug: Print varible value
    # - name: Print AUTH Token Data
    #   ansible.builtin.debug:
    #     msg: "Authorization Bearer Token: {{ tenant_auth_response.json.data }}"

    ###
    # OGR-INFO Get: ALL
    - name: Get ORG Info
      netapp.storagegrid.na_sg_org_info:
        gather_subset:
          # - all
          # - org/containers
          # - org/usage
          - org/groups
          # - org/users
          # - org/users/current-user/s3-access-keys
          # - org/users/root
        <<: *org_auth
      register: grid_info_results

    ###
    # Debug: Print varible value
    - name: Print GRID Response
      ansible.builtin.debug:
        var: grid_info_results

