###
# StorageGRID: Tenant Management
# Description:
# Creates / Modifies / Deletes Tenants
# 
# Requirements:
#  - Grid Administrator
#  - Tenant Administrator - Updates Can't be done by a normal tenant user
#  - Tenant Account ID (Optional) - Can lookup Teant account_id byname
#  - tenant user name & access_key required for deletion
#  - Delete requires all containers to be removed before the tenant can be deleted
#  - 
###
---
- name: "GRID: Tenant Management"
  hosts: localhost
  gather_facts: false
  collections:
    - netapp.storagegrid
  
  vars_files:
    # - vars/vars_sg_exampleLab.yml
    - vars/vars_sg_tenant_appid01.yml
  vars:
    state:            present
    grid:
      api_base_url:   https://192.168.7.215
      admin_username: root
      admin_passwd:   netapp1234
    tenant:
      name:           AppID01
    
    find_tenant_id:   true  # Set to true to enable tenant_id lookup byname
    tenant_id:              # Enter account_id if not looking up byname && find_tenant_id == false
    
    ###
    # Authentication Bearer Tokens 
    # Grid Authorization Token
    grid_auth: &grid_auth
      api_url:        "{{ grid.api_base_url }}"
      auth_token:     "{{ auth_response.json.data }}"
      validate_certs: false
    # Tenant Authorization Token
    tenant_auth: &org_auth
      api_url:        "{{ grid.api_base_url }}"
      auth_token:     "{{ tenant_auth_response.json.data }}"
      validate_certs: false


  tasks:
  ###
  # GRID API Authorization Token
    - name: Get GRID authorization token
      uri:
        url: "{{ grid.api_base_url }}/api/v3/authorize"
        method: POST
        validate_certs: false
        body_format: json
        body:
          {
            "username": "{{ grid.admin_username }}",
            "password": "{{ grid.admin_passwd }}",
            "cookie": false,
            "csrfToken": false,
          }
      register: auth_response


    ###
    # GRID: Create / Modify tenant
    - name: Create or Modify a StorageGRID Tenant Account
      netapp.storagegrid.na_sg_grid_account:
        <<: *grid_auth

        state:            "{{ state }}"
        name:             "{{ tenant.name }}"
        password:         "{{ tenant.admin_passwd }}"

        protocol:         "{{ tenant.protocol | default('s3') }}"
        management:       "{{ tenant.management | default('true') }}"  # Default: true - Tenant account can login to tenant portal
        quota_size:       "{{ tenant.quota_size | default('0') }}"  # Defaults to '0'
        quota_size_unit:  "{{ tenant.quota_size_unit | default('gb') }}"  # Defaults to 'gb'
        update_password:  on_create # Default: on_create
        allow_platform_services: "{{ tenant.allow_platform_services | default('false') }}"
        use_own_identity_source: "{{ tenant.use_own_identity_source | default('false') }}"
      register: account
      when: state == 'present'

  ###
  # Lookup Tenant account_id - set find_account_id to `true` 
    - name: Lookup Tenant account_id byname
      block:

    ###
    # GRID INFO Collection
      - name: Get Grid INFO
        netapp.storagegrid.na_sg_grid_info:
          <<: *grid_auth
          gather_subset:
            # - all
            - grid/accounts
        register: grid_info_results

    ###
    # Debug: Print GRID-INFO Response
      # - name: Print GRID-INFO Response
      #   debug:
      #     var: grid_info_results

    ###
    # Debug: Print Tenant Account ID Byname
      # - name: "Print Tenant ID for {{ tenant.name }}"
      #   debug:
      #     msg:
      #       - "Tenant Name: {{ item.name }} Tenant ID: {{ item.id }}"
      #   with_items:
      #     - "{{ grid_info_results.sg_info['grid/accounts'].data }}"
      #   when: item.name == tenant.name

    ###
    # Find account_id for given tenant name
      - name: Set_Fact - tenant_id
        set_fact:
          tenant_id: "{{ item.id }}"
        with_items:
          - "{{ grid_info_results.sg_info['grid/accounts'].data }}"
        when: item.name|lower == tenant.name|lower

    ###
    # Debug: Print varible value
      # - name: 'DEBUG: Print Varible: tenant_id'
      #   debug:
      #     msg: "from set_fact: {{ tenant_id }}"

      # when: find_tenant_id is true 
    
    # End block
    ###

    ###
    # Tenant Authorization Token
    - name: Get Tenant Administrator user authorization token
      uri:
        url: "{{ grid.api_base_url }}/api/v3/authorize"
        method: POST
        validate_certs: false
        body_format: json
        body:
          {
            "accountId": "{{ tenant_id }}",
            "username": "{{ tenant.admin_username }}",
            "password": "{{ tenant.admin_passwd }}",
            "cookie": false,
            "csrfToken": false,
          }
      register: tenant_auth_response


    ###
    # GRID: Delete tenant
    # Requirements: All buckets (containers) need to be removed prior to deletion
    
    ###
    # Removes containers 
    - name: Delete StorageGRID Tenant Containers
      netapp.storagegrid.na_sg_org_container:
        <<: *org_auth

        state:            "{{ state }}"
        name:             "{{ tenant.name }}"

      when: state == 'absent'
    

    ###
    # Removes Tenant
    - name: Delete a StorageGRID Tenant Account
      netapp.storagegrid.na_sg_grid_account:
        <<: *grid_auth

        state:            "{{ state }}"
        name:             "{{ tenant.name }}"

        protocol:         "{{ tenant.protocol | default('s3') }}"

      when: state == 'absent'