################################################################################
#
#   Author      :   Ken Hillier
#   Date        :   25 January 2023
#
#   Description :   Workflow to illustrate get CERT by name
#
#   Dependencies: netapp.ontap collection
#
################################################################################
---
- hosts:                localhost
  name:                 Get Cert by name
  gather_facts:         false
  collections:
    -                   ansible.builtin
    -                   netapp.ontap
  vars:
    login: &login
      hostname:         "{{ netapp_hostname }}"
      username:         "{{ netapp_username }}"
      password:         "{{ netapp_password }}"
      https:            "{{ https }}"
      validate_certs:   "{{ validate_certs }}"
    state:              present

  vars_files:
    - vars/vars_ontap_ontap-cl01.yml


  tasks:

  
  - name: run ONTAP gather facts for aggregate info and volume info with fields section
    netapp.ontap.na_ontap_rest_info:
      <<: *login

      use_rest: Always

      fields:
        - '*'
      gather_subset:
        # - storage/aggregates
        # - storage/volumes
        - security/certificates
        # - security/key-managers
    register: rest_info_results

  ###
  # Debug: Print GRID-INFO Response
  - name: Print GRID-INFO Response
    debug:
      var: rest_info_results
  
  ###
  # Debug: Print Cert UUID Byname
  # - name: "Print Tenant ID for {{ cert.name }}"
  - name: "Print Certificate Names"
    debug:
      msg:
        - "Certificate Name: {{ item.name }} ID: {{ item.id }}"
    with_items:
      - "{{ grid_info_results.sg_info['grid/accounts'].data }}"
    # when: item.name == cert.name

  ###
  # Find account_id for given tenant name
    # - name: Set_Fact - tenant_id
    #   set_fact:
    #     cert_uuid: "{{ item.id }}"
    #   with_items:
    #     - "{{ rest_info_results.sg_info['grid/accounts'].data }}"
    #   when: item.name|lower == tenant.name|lower