---
- hosts: localhost
  name: Snapshot Policy Management
  gather_facts: false
  collections:
    - netapp.ontap

  vars:
    netapp_hostname:  192.168.7.200
    netapp_username:  admin

    ss_policy:

    login: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter the NetApp Admin Password"
      private: yes
  # vars_files:
  #   - vars_files.yml

  tasks:

  - name: Create Snapshot policy with multiple schedules
    na_ontap_snapshot_policy:
      state: present
      name: ansible2
      schedule: ['hourly', 'daily', 'weekly', 'monthly', '5min']
      prefix: ['hourly', 'daily', 'weekly', 'monthly', '5min']
      count: [1, 2, 3, 4, 5]
      enabled: True

      <<: *login
    # register: ontap_info

  - name: Display Captured info
    debug:
        msg: "{{ ontap_info.ontap_info }}"
